name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  OPENSAL_BUILD_DIR: ${{ github.workspace }}/build

jobs:
  build:
    runs-on: windows-2019
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Populate build
        run: ${{ github.workspace }}\src\vcxproj\!populate_build_dir.cmd

      - name: Build
        run: ${{ github.workspace }}\src\vcxproj\build.cmd
